repos:
  # Hooks de base
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  # ESLint pour le frontend
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.30.1
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^9.30.1
          - '@eslint/js@^9.30.1'
          - typescript-eslint@^8.35.1
          - eslint-plugin-react-hooks@^5.2.0
          - eslint-plugin-react-refresh@^0.4.20

  # Prettier pour le formatage
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$
        types: [file]

  # Tests pour le frontend
  - repo: local
    hooks:
      - id: frontend-tests
        name: Frontend Tests
        entry: npm run test:run
        language: system
        pass_filenames: false
        always_run: true

  # Vérification des dépendances
  - repo: local
    hooks:
      - id: check-dependencies
        name: Check Dependencies
        entry: npm audit --audit-level=moderate
        language: system
        pass_filenames: false
        always_run: true
